{% set version = "0.0.91" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-strawr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/strawr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/strawr/strawr_{{ version }}.tar.gz
  sha256: 55e06f35613b8cef8405498393e15591c06281004332ad532f6eb8f180b06cd9

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - libcurl
    - zlib
  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('strawr')"           # [not win]
    - "\"%R%\" -e \"library('strawr')\""  # [win]

about:
  home: https://github.com/aidenlab/straw/tree/master/R
  license: MIT
  summary: API for fast data extraction for .hic files that provides programmatic access to the matrices. It doesn't store the pointer data for all the matrices, only the one queried, and currently we are only supporting matrices (not vectors).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
